Added picture support
HackGT/hackgt-org-website pull request #26
Opened 2017-09-21 20:47 UTC by jacobj10

2017-09-22 02:12 UTC, illegalprime commented
That looks great! But the images are not always square and when people don't have a social link it shows a dash sign. Maybe it just shouldn't show anything if they don't have links? And I think fitting the images to the whole area is a css fix.

2017-09-22 02:16 UTC, illegalprime requested changes
Beautiful!

2017-09-22 02:16 UTC, illegalprime commented on _pages/about.html
> +                            <img class="img-responsive" src="/static/images/members/{{ member.name }}" alt="" width="300" height="300">
Use a background div image so you can have it zoom-fill: https://stackoverflow.com/a/11763434

2017-09-22 02:16 UTC, illegalprime commented on _pages/about.html
> +                                            <i class="fa fa-minus"></i>
Do not show anything if they don't have it.

2017-09-22 23:08 UTC, jacobj10 commented
all right, should be fixed!

2017-09-24 16:28 UTC, illegalprime approved these changes

2017-09-24 16:29 UTC, merged