Staging area for blog content
HackGT/hackgt-org-website pull request #70
Opened 2018-03-20 18:41 UTC by ehsanmasdar

2018-05-17 18:53 UTC, bunsenmcdubbs requested changes

2018-05-17 18:53 UTC, bunsenmcdubbs commented on _posts/2018-03-20-infra.md
> +# Motivation
This should probably be `##` (h2). The blog post title is already `h1` so semantically all the headers inside the post should be one level below that.

2018-05-17 23:46 UTC, bunsenmcdubbs approved these changes

2018-05-17 23:46 UTC, bunsenmcdubbs reviewed
I think we should change the date of the blog posts to when it is actually published (not March lol)

2018-05-18 05:09 UTC, kexin-zhang commented
The footer looks like this for me... 

![image](https://user-images.githubusercontent.com/17093911/40216937-e22c7ba4-5a1e-11e8-9659-c42c5e27e69c.png)

2018-05-18 16:16 UTC, kexin-zhang reviewed
Alright, so Jekyll was rendering the page weirdly because of how we were truncating the preview for the blog post, but it's fixed now. I think we're good to merge this once we get an image for the postgres post and fix the date of the other post.

2018-05-22 04:48 UTC, kexin-zhang approved these changes

2018-05-22 04:49 UTC, merged